package com.mlevngr.inknote.markdown

/** Removes the title line generated by older InkNote versions from the Markdown body. */
object LegacyNoteBodyMigration {
    fun separateTitle(markdown: String, noteTitle: String): String {
        val lines = markdown.split('\n', ignoreCase = false, limit = Int.MAX_VALUE)
        if (lines.firstOrNull() != "# $noteTitle") return markdown

        val bodyStart = if (lines.getOrNull(1).isNullOrEmpty()) 2 else 1
        return lines.drop(bodyStart).joinToString("\n")
    }
}
